#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from diffusers import StableDiffusionPipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)
    
url = "https://huggingface.co/asiryan/absolutereality/blob/main/absolutereality_v181.safetensors"
pipe = StableDiffusionPipeline.from_single_file(
    url,
    torch_dtype=torch.float16
)

pipe.save_pretrained(MODEL_CACHE)
